export async function GET(request) {
  const mockCampaignData = {
    campaigns: [
      {
        campaignId: "cmp1",
        name: "Summer Sale 2024",
        adGroups: [
          {
            adGroupId: "ag1",
            name: "Google Ads - Search",
            metrics: [
              {
                date: "2024-08-01",
                device: "mobile",
                location: "USA",
                impressions: 15000,
                clicks: 1200,
                conversions: 100,
                spend: 500,
              },
              {
                date: "2024-08-02",
                device: "desktop",
                location: "USA",
                impressions: 8000,
                clicks: 900,
                conversions: 70,
                spend: 300,
              },
              {
                date: "2024-08-03",
                device: "mobile",
                location: "Canada",
                impressions: 16000,
                clicks: 1300,
                conversions: 110,
                spend: 520,
              },
              {
                date: "2024-08-04",
                device: "desktop",
                location: "Canada",
                impressions: 6000,
                clicks: 700,
                conversions: 60,
                spend: 250,
              },
              {
                date: "2024-08-05",
                device: "tablet",
                location: "USA",
                impressions: 9000,
                clicks: 800,
                conversions: 75,
                spend: 320,
              },
            ],
          },
          {
            adGroupId: "ag2",
            name: "Facebook Ads",
            metrics: [
              {
                date: "2024-08-01",
                device: "mobile",
                location: "UK",
                impressions: 12000,
                clicks: 1000,
                conversions: 90,
                spend: 400,
              },
              {
                date: "2024-08-02",
                device: "desktop",
                location: "UK",
                impressions: 7000,
                clicks: 800,
                conversions: 75,
                spend: 300,
              },
              {
                date: "2024-08-03",
                device: "tablet",
                location: "Canada",
                impressions: 11000,
                clicks: 900,
                conversions: 85,
                spend: 350,
              },
              {
                date: "2024-08-04",
                device: "mobile",
                location: "Canada",
                impressions: 14000,
                clicks: 1100,
                conversions: 95,
                spend: 450,
              },
              {
                date: "2024-08-05",
                device: "desktop",
                location: "USA",
                impressions: 13000,
                clicks: 1050,
                conversions: 100,
                spend: 480,
              },
            ],
          },
        ],
      },
      {
        campaignId: "cmp2",
        name: "Back to School 2024",
        adGroups: [
          {
            adGroupId: "ag1",
            name: "Google Ads - Search",
            metrics: [
              {
                date: "2024-08-01",
                device: "mobile",
                location: "Australia",
                impressions: 14000,
                clicks: 1100,
                conversions: 85,
                spend: 450,
              },
              {
                date: "2024-08-02",
                device: "desktop",
                location: "Australia",
                impressions: 12000,
                clicks: 900,
                conversions: 80,
                spend: 400,
              },
              {
                date: "2024-08-03",
                device: "tablet",
                location: "New Zealand",
                impressions: 10000,
                clicks: 800,
                conversions: 70,
                spend: 350,
              },
              {
                date: "2024-08-04",
                device: "mobile",
                location: "New Zealand",
                impressions: 11000,
                clicks: 850,
                conversions: 75,
                spend: 370,
              },
              {
                date: "2024-08-05",
                device: "desktop",
                location: "UK",
                impressions: 9000,
                clicks: 750,
                conversions: 65,
                spend: 300,
              },
            ],
          },
          {
            adGroupId: "ag2",
            name: "Facebook Ads",
            metrics: [
              {
                date: "2024-08-01",
                device: "desktop",
                location: "USA",
                impressions: 8000,
                clicks: 700,
                conversions: 60,
                spend: 320,
              },
              {
                date: "2024-08-02",
                device: "tablet",
                location: "Canada",
                impressions: 6000,
                clicks: 500,
                conversions: 50,
                spend: 250,
              },
              {
                date: "2024-08-03",
                device: "mobile",
                location: "UK",
                impressions: 7000,
                clicks: 600,
                conversions: 55,
                spend: 280,
              },
              {
                date: "2024-08-04",
                device: "desktop",
                location: "Australia",
                impressions: 10000,
                clicks: 900,
                conversions: 75,
                spend: 400,
              },
              {
                date: "2024-08-05",
                device: "mobile",
                location: "USA",
                impressions: 13000,
                clicks: 1050,
                conversions: 100,
                spend: 480,
              },
            ],
          },
        ],
      },
      {
        campaignId: "cmp3",
        name: "Holiday Promotions 2024",
        adGroups: [
          {
            adGroupId: "ag1",
            name: "Google Ads - Search",
            metrics: [
              {
                date: "2024-08-01",
                device: "mobile",
                location: "USA",
                impressions: 15000,
                clicks: 1200,
                conversions: 100,
                spend: 500,
              },
              {
                date: "2024-08-02",
                device: "desktop",
                location: "UK",
                impressions: 10000,
                clicks: 900,
                conversions: 80,
                spend: 450,
              },
              {
                date: "2024-08-03",
                device: "tablet",
                location: "Canada",
                impressions: 12000,
                clicks: 1000,
                conversions: 90,
                spend: 400,
              },
              {
                date: "2024-08-04",
                device: "mobile",
                location: "Australia",
                impressions: 16000,
                clicks: 1300,
                conversions: 110,
                spend: 550,
              },
              {
                date: "2024-08-05",
                device: "desktop",
                location: "USA",
                impressions: 14000,
                clicks: 1150,
                conversions: 105,
                spend: 520,
              },
            ],
          },
          {
            adGroupId: "ag2",
            name: "Facebook Ads",
            metrics: [
              {
                date: "2024-08-01",
                device: "mobile",
                location: "UK",
                impressions: 9000,
                clicks: 800,
                conversions: 70,
                spend: 380,
              },
              {
                date: "2024-08-02",
                device: "desktop",
                location: "Canada",
                impressions: 7000,
                clicks: 600,
                conversions: 60,
                spend: 300,
              },
              {
                date: "2024-08-03",
                device: "tablet",
                location: "Australia",
                impressions: 11000,
                clicks: 950,
                conversions: 85,
                spend: 420,
              },
              {
                date: "2024-08-04",
                device: "mobile",
                location: "USA",
                impressions: 13000,
                clicks: 1100,
                conversions: 95,
                spend: 460,
              },
              {
                date: "2024-08-05",
                device: "desktop",
                location: "UK",
                impressions: 8000,
                clicks: 700,
                conversions: 65,
                spend: 340,
              },
            ],
          },
        ],
      },
      {
        campaignId: "cmp4",
        name: "New Year Special 2025",
        adGroups: [
          {
            adGroupId: "ag1",
            name: "Google Ads - Search",
            metrics: [
              {
                date: "2024-08-01",
                device: "desktop",
                location: "USA",
                impressions: 10000,
                clicks: 850,
                conversions: 80,
                spend: 400,
              },
              {
                date: "2024-08-02",
                device: "mobile",
                location: "Canada",
                impressions: 12000,
                clicks: 950,
                conversions: 85,
                spend: 450,
              },
              {
                date: "2024-08-03",
                device: "tablet",
                location: "UK",
                impressions: 8000,
                clicks: 750,
                conversions: 70,
                spend: 350,
              },
              {
                date: "2024-08-04",
                device: "desktop",
                location: "Australia",
                impressions: 11000,
                clicks: 900,
                conversions: 75,
                spend: 370,
              },
              {
                date: "2024-08-05",
                device: "mobile",
                location: "USA",
                impressions: 13000,
                clicks: 1050,
                conversions: 95,
                spend: 480,
              },
            ],
          },
          {
            adGroupId: "ag2",
            name: "Facebook Ads",
            metrics: [
              {
                date: "2024-08-01",
                device: "mobile",
                location: "Australia",
                impressions: 9000,
                clicks: 800,
                conversions: 70,
                spend: 350,
              },
              {
                date: "2024-08-02",
                device: "desktop",
                location: "New Zealand",
                impressions: 7000,
                clicks: 600,
                conversions: 60,
                spend: 280,
              },
              {
                date: "2024-08-03",
                device: "tablet",
                location: "UK",
                impressions: 11000,
                clicks: 900,
                conversions: 85,
                spend: 420,
              },
              {
                date: "2024-08-04",
                device: "mobile",
                location: "Canada",
                impressions: 14000,
                clicks: 1100,
                conversions: 95,
                spend: 460,
              },
              {
                date: "2024-08-05",
                device: "desktop",
                location: "USA",
                impressions: 15000,
                clicks: 1200,
                conversions: 100,
                spend: 500,
              },
            ],
          },
        ],
      },
      {
        campaignId: "cmp5",
        name: "Spring Launch 2025",
        adGroups: [
          {
            adGroupId: "ag1",
            name: "Google Ads - Search",
            metrics: [
              {
                date: "2024-08-01",
                device: "tablet",
                location: "USA",
                impressions: 9000,
                clicks: 800,
                conversions: 70,
                spend: 350,
              },
              {
                date: "2024-08-02",
                device: "desktop",
                location: "UK",
                impressions: 11000,
                clicks: 950,
                conversions: 85,
                spend: 420,
              },
              {
                date: "2024-08-03",
                device: "mobile",
                location: "Canada",
                impressions: 14000,
                clicks: 1100,
                conversions: 95,
                spend: 460,
              },
              {
                date: "2024-08-04",
                device: "tablet",
                location: "Australia",
                impressions: 15000,
                clicks: 1200,
                conversions: 100,
                spend: 500,
              },
              {
                date: "2024-08-05",
                device: "desktop",
                location: "New Zealand",
                impressions: 13000,
                clicks: 1050,
                conversions: 90,
                spend: 480,
              },
            ],
          },
          {
            adGroupId: "ag2",
            name: "Facebook Ads",
            metrics: [
              {
                date: "2024-08-01",
                device: "desktop",
                location: "USA",
                impressions: 16000,
                clicks: 1300,
                conversions: 110,
                spend: 520,
              },
              {
                date: "2024-08-02",
                device: "mobile",
                location: "Canada",
                impressions: 15000,
                clicks: 1200,
                conversions: 100,
                spend: 500,
              },
              {
                date: "2024-08-03",
                device: "tablet",
                location: "Australia",
                impressions: 17000,
                clicks: 1400,
                conversions: 120,
                spend: 580,
              },
              {
                date: "2024-08-04",
                device: "desktop",
                location: "UK",
                impressions: 18000,
                clicks: 1500,
                conversions: 130,
                spend: 600,
              },
              {
                date: "2024-08-05",
                device: "mobile",
                location: "New Zealand",
                impressions: 19000,
                clicks: 1600,
                conversions: 140,
                spend: 650,
              },
            ],
          },
        ],
      },
    ],
  };

  return new Response(JSON.stringify(mockCampaignData), {
    status: 200,
    headers: { "Content-Type": "application/json" },
  });
}
